### ISSUE TITLE
zitadel and https

### ISSUE THREAD

**Issue by ekarlso** [itpropro/nuxt-oidc-auth#67]
I configured the following and I get 
```
[GET] "https://localhost:8080/.well-known/openid-configuration": <no response> fetch failed
```

```typescript
  oidc: {
    defaultProvider: 'zitadel',
    providers: {
      zitadel: {
        clientId: '282949336457872899',
        clientSecret: '', // Works with PKCE and Code flow, just leave empty for PKCE
        redirectUri: 'http://localhost:3000/auth/zitadel/callback',
        baseUrl: 'http://localhost:8080',
        audience: '', // Specify for id token validation, normally same as clientId
        logoutRedirectUri: 'https://google.com', // Needs to be registered in Zitadel portal
        authenticationScheme: 'none', // Set this to 'header' if Code is used instead of PKCE
      },
    },
    session: {
      expirationCheck: true,
      automaticRefresh: true,
      expirationThreshold: 3600,
    },
    middleware: {
      globalMiddlewareEnabled: true,
      customLoginPage: true,
    },
    devMode: {
      enabled: false,
      generateAccessToken: true,
      userName: 'Test User',
      userInfo: { providerName: 'test' },
      claims: { customclaim01: 'foo', customclaim02: 'bar' },
      issuer: 'dev-issuer',
      audience: 'dev-app',
      subject: 'dev-user',
    },
  },
```

**Comment by christianOB** [comment]
As a workaround does adding this to your zitadel provider config fix it?
```
// @ts-expect-error
openIdConfiguration: 'http://localhost:8080/.well-known/openid-configuration',
```

**Comment by ekarlso** [comment]
Hi, no that didn't work :)

**Comment by itpropro** [comment]
You have the wrong base url in your config. The base url is the one form Zitadel. It should have the format "https://PROJECT.REGION.zitadel.cloud".
Check the docs on the Zitadel provider: https://nuxtoidc.cloud/provider/zitadel

**Comment by ekarlso** [comment]
I asked in the other thread that this would not work with localdev where you don't have the https.. It is totally normal to run Zitadel for Local development and it would be nice to be able to use the same setup.

**Comment by itpropro** [comment]
> I asked in the other thread that this would not work with localdev where you don't have the https.. It is totally normal to run Zitadel for Local development and it would be nice to be able to use the same setup.

Zitadel works fine in local development, I used it to test all the flows provided by them. You just have to set the Zitadel base url to your Zitadel project, register your redirect Uri to your localhost and put that into your nuxt config.

**Comment by ekarlso** [comment]
Well, I did that using the playground with the config above and it broke

**Comment by itpropro** [comment]
What is the error message? Have you configured Zitadel correctly (PKCE flow, redirect uri). As other people are using the Zitadel provider as well, there has to be something off either with your local config or with the Zitadel config.
This is my redirect uris
![image](https://github.com/user-attachments/assets/94460646-9cf6-4b1e-aef7-c403310bf6d3)
And this is my auth config
![image](https://github.com/user-attachments/assets/5bc98e22-a0ec-4fef-90ad-aa02cd5bdbec)
![image](https://github.com/user-attachments/assets/64ddcaab-5c67-44d2-bedb-5e4c432b0549)

**Comment by ekarlso** [comment]
Yes, I triple checked the Zitadel settings
```
oidc: {
    defaultProvider: 'zitadel',
    providers: {
      zitadel: {
        clientId: '282949336457872899@tradero',
        clientSecret: '', // Works with PKCE and Code flow, just leave empty for PKCE
        redirectUri: 'http://localhost:3000/auth/zitadel/callback',
        baseUrl: 'http://localhost:8080',
        // audience: '', // Specify for id token validation, normally same as clientId
      },
    },
    session: {
      expirationCheck: true,
      automaticRefresh: true,
      expirationThreshold: 3600,
    },
    middleware: {
      globalMiddlewareEnabled: true,
      customLoginPage: true,
    },
  },```

```
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)  
  at new NodeError (node:internal/errors:405:5)  
  at ServerResponse.setHeader (node:_http_outgoing:648:11)  
  at sendRedirect (./node_modules/h3/dist/index.mjs:767:18)  
  at oidcErrorHandler (/home/ekarlso/exch/nuxt-oidc-auth/node_modules/.pnpm/nuxt-oidc-auth@0.18.0_@nuxt+devtools@1.5.2_rollup@4.24.0_vite@5.4.8_@types+node@22.7.4_terser_muvhm52dwrhesnwutro62dipqy/node_modules/nuxt-oidc-auth/dist/runtime/server/utils/oidc.js:105:10)  
  at Object.handler (/home/ekarlso/exch/nuxt-oidc-auth/node_modules/.pnpm/nuxt-oidc-auth@0.18.0_@nuxt+devtools@1.5.2_rollup@4.24.0_vite@5.4.8_@types+node@22.7.4_terser_muvhm52dwrhesnwutro62dipqy/node_modules/nuxt-oidc-auth/dist/runtime/server/lib/oidc.js:143:14)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./node_modules/h3/dist/index.mjs:1978:19  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2270:7)


 ERROR  [nitro] [unhandledRejection] Cannot set headers after they are sent to the client

  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at ServerResponse.setHeader (node:_http_outgoing:648:11)
  at setCookie (node_modules/h3/dist/index.mjs:612:18)
  at updateSession (node_modules/h3/dist/index.mjs:1384:5)
  at async getSession (node_modules/h3/dist/index.mjs:1369:5)
  at async useSession (node_modules/h3/dist/index.mjs:1311:3)
  at clearUserSession (/home/ekarlso/exch/nuxt-oidc-auth/node_modules/.pnpm/nuxt-oidc-auth@0.18.0_@nuxt+devtools@1.5.2_rollup@4.24.0_vite@5.4.8_@types+node@22.7.4_terser_muvhm52dwrhesnwutro62dipqy/node_modules/nuxt-oidc-auth/dist/runtime/server/utils/session.js:18:19)

[nuxt-oidc-auth] ℹ [nuxt-oidc-auth]: Skipping JWT token parsing

 ERROR  [nuxt] [request error] [unhandled] [500] [GET] "https://localhost:8080/.well-known/openid-configuration": <no response> fetch failed
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.4747642d.mjs:261:14)  
  at async $fetch2 (./node_modules/ofetch/dist/shared/ofetch.4747642d.mjs:304:15)  
  at Object.openIdConfiguration (/home/ekarlso/exch/nuxt-oidc-auth/node_modules/.pnpm/nuxt-oidc-auth@0.18.0_@nuxt+devtools@1.5.2_rollup@4.24.0_vite@5.4.8_@types+node@22.7.4_terser_muvhm52dwrhesnwutro62dipqy/node_modules/nuxt-oidc-auth/dist/runtime/providers/zitadel.js:37:12)  
  at Object.handler (/home/ekarlso/exch/nuxt-oidc-auth/node_modules/.pnpm/nuxt-oidc-auth@0.18.0_@nuxt+devtools@1.5.2_rollup@4.24.0_vite@5.4.8_@types+node@22.7.4_terser_muvhm52dwrhesnwutro62dipqy/node_modules/nuxt-oidc-auth/dist/runtime/server/lib/oidc.js:149:235)  
  at async ./node_modules/h3/dist/index.mjs:1978:19  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2270:7)
```

**Comment by itpropro** [comment]
It looks like the openid-configuration is not available. Have you checked the path https://localhost:8080/.well-known/openid-configuration if there is a valid openid-config there and if it has a jwks in there that was used to sign the id token?
If you don't want to use that at all, you can just set `validateIdToken` to `false`.

**Comment by ekarlso** [comment]
Yes it is there but it is served as http://... by default I think when you ue their docker-compose setup

**Comment by itpropro** [comment]
> Yes it is there but it is served as http://... by default I think when you ue their docker-compose setup

It took a while, but I understand your problem now :)
Please turn off id token validation by setting `validateIdToken` to `false` for local development. It wouldn't make sense to implement a functionality to support http, because that would only be in scenarios, where validating the token wouldn't provide any security benefits.
