### ISSUE TITLE
Error together with undio

### ISSUE THREAD

**Issue by ekarlso** [itpropro/nuxt-oidc-auth#70]
Have you seen this together with Undio for b64 decoding ? 

```
ERROR  [nuxt] [request error] [unhandled] [500] Invalid character
  at atob (node:buffer:1269:13)  
  at _base64Decode (/frontend/node_modules/.pnpm/undio@0.2.0/node_modules/undio/dist/index.mjs:109:16)  
  at base64ToUint8Array (/frontend/node_modules/.pnpm/undio@0.2.0/node_modules/undio/dist/index.mjs:68:10)  
  at encryptToken (/frontend/node_modules/.pnpm/nuxt-oidc-auth@0.18.0_@nuxt+devtools@1.5.1_rollup@4.21.2_vite@5.4.3_@types+node@20.11.24_sass_2ar6elgzmn2qffnorthse6de4a/node_modules/nuxt-oidc-auth/dist/runtime/server/utils/security.js:43:51)  
  at Object.handler (/frontend/node_modules/.pnpm/nuxt-oidc-auth@0.18.0_@nuxt+devtools@1.5.1_rollup@4.21.2_vite@5.4.3_@types+node@20.11.24_sass_2ar6elgzmn2qffnorthse6de4a/node_modules/nuxt-oidc-auth/dist/runtime/server/lib/oidc.js:201:28)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async /frontend/node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:19  
  at async Object.callAsync (/frontend/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (/frontend/node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)
```

**Comment by ekarlso** [comment]
To anyone who wonders this is due to a bad NUXT_OIDC_TOKEN_KEY not being properly formatted/quoted
